# Generated by Django 4.0.5 on 2022-06-09 20:46

from django.db import migrations, models
import edc_utils.date


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='report_datetime',
            field=models.DateTimeField(default=edc_utils.date.get_utcnow),
        ),
        migrations.AddField(
            model_name='reports',
            name='sql_view_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
